"""criação da tabela vendas

Revision ID: 9614bf6b8bdc
Revises: 
Create Date: 2026-04-26 18:36:48.872077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9614bf6b8bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmacia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=False),
    sa.Column('nif', sa.String(), nullable=False),
    sa.Column('telefone_whatsapp', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso', sa.Integer(), nullable=False),
    sa.Column('telefone_whatsapp', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['farmacia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('data', sa.String(length=250), nullable=False),
    sa.Column('hora', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['farmacia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('preço', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('validade', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['farmacia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'user_id', name='_nome_user_uc')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('preço', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('hora', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adicionado_por_id', sa.Integer(), nullable=False),
    sa.Column('obs', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['adicionado_por_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['farmacia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('medicamento')
    op.drop_table('historia')
    op.drop_table('funcionario')
    op.drop_table('farmacia')
    # ### end Alembic commands ###
